services:
  postgres:
    image: postgres:16-alpine
    container_name: babydaily-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=babydaily
      - TZ=Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
