services:

  backend:
    image: babydaily-backend
    container_name: babydaily-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=babydaily
      - JWT_SECRET=super-secret-key
      - TZ=Asia/Shanghai
      - ENABLE_DEV_LOGIN=true
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: babydaily-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=babydaily
      - TZ=Asia/Shanghai
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  frontend:
    image: babydaily-frontend
    container_name: babydaily-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
