version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: babydaily-redis
    restart: always
    ports:
      - "63790:6379"

  backend:
    build: ./backend
    container_name: babydaily-backend
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - JWT_SECRET=super-secret-key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_PATH=database/babydaily.sqlite
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database

  frontend:
    build: ./frontend
    container_name: babydaily-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
